/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lars' at '03.03.15 14:30' with Gradle 2.1
 *
 * @author lars, @date 03.03.15 14:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
